[project]
name = "q3-assign-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "cryptography>=44.0.2",
    "fernet>=1.0.1",
    "streamlit>=1.40.1",
]

[tool.streamlit]
package-mode = false